name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        komapper: [ 1.3.0, 1.4.0 ]
        kotlin: [ 1.6.21, 1.7.0, 1.7.10, 1.7.20 ]
        ksp: [ 1.0.6 ]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Assemble and Check
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
          arguments: |
            assemble
            check
            -PkomapperVersion=${{ matrix.komapper }}
            -PkotlinVersion=${{ matrix.kotlin }}
            -PkspVersion=${{ matrix.ksp }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./**/build/reports
