name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  kotlin-1_7:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Komapper v1.12.0 do not work with Kotlin v1.7.22
        kotlin: [ 1.7.22 ]
        ksp: [ 1.0.8 ]
        komapper: [ 1.3.0, 1.4.0, 1.5.0, 1.6.1, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.11.0 ]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Assemble and Check
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1
          arguments: |
            assemble
            check
            -PkomapperVersion=${{ matrix.komapper }}
            -PkotlinVersion=${{ matrix.kotlin }}
            -PkspVersion=${{ matrix.ksp }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./**/build/reports

  kotlin-1_8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kotlin: [ 1.8.22 ]
        ksp: [ 1.0.11 ]
        komapper: [ 1.3.0, 1.4.0, 1.5.0, 1.6.1, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0 ]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Assemble and Check
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.8.3
          arguments: |
            assemble
            check
            -PkomapperVersion=${{ matrix.komapper }}
            -PkotlinVersion=${{ matrix.kotlin }}
            -PkspVersion=${{ matrix.ksp }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./**/build/reports

  kotlin-1_9:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kotlin: [ 1.9.0 ]
        ksp: [ 1.0.11, 1.0.12 ]
        komapper: [ 1.3.0, 1.4.0, 1.5.0, 1.6.1, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0 ]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Assemble and Check
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.8.3
          arguments: |
            assemble
            check
            -PkomapperVersion=${{ matrix.komapper }}
            -PkotlinVersion=${{ matrix.kotlin }}
            -PkspVersion=${{ matrix.ksp }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./**/build/reports
